### PR TITLE
Metadata parameter lowercase, request json field and others problems

### PR DESCRIPTION
**Pull request by intersecato**
Metadata parameter has been made lowercase by LuckPerms some time ago.
I honestly have no idea if anything else was changed.

(I saw now that you are a member of LuckPerms, I hope it is not an outdated wrapper because it would be very convenient for us)

### CODE REVIEW

**Comment by intersecato** [comment]
https://github.com/tadhgboyle/LuckPerms-API-Wrapper/blob/2b5a39f23e9277d618c134382356808e26bc49c6/src/Concerns/HasPermissions.php#L40-L55

In HTTP request, data should be sent in the request body, not in the 'json' field of the request options.

**Comment by intersecato** [comment]
In this way, the data is sent in the body of the POST request as form parameters, and in the GET request as query parameters

**Comment by intersecato** [comment]
There are also other problems:

https://github.com/tadhgboyle/LuckPerms-API-Wrapper/blob/2b5a39f23e9277d618c134382356808e26bc49c6/src/Concerns/HasPermissions.php#L59-L62

Here if the permission is undefined there will be only the `result` index in the json and not the `node` one. This unequivocally leads to an error.



https://github.com/tadhgboyle/LuckPerms-API-Wrapper/blob/2b5a39f23e9277d618c134382356808e26bc49c6/src/Repository/Repository.php#L52-L55

LuckPermsAPI\Repository\Repository::json(): Return value must be of type array, null returned.

**Comment by tadhgboyle** [comment]
Thank you so much!

> I saw now that you are a member of LuckPerms, I hope it is not an outdated wrapper because it would be very convenient for us

It is not an official one so there is no promise that it'll be up to date (as you can see with the problems you've found 😅 

> There are also other problems:

Are you able to put these fixes in this PR?

**Comment by intersecato** [comment]
Hi @tadhgboyle, 
I fixed everything. I assumed that when a permission is undefined it returns false to checkPermission, I think it is the best thing to do to avoid having to do further checks on the PHP side if the user implements the library.

Let me know what you think of the changes.

**Review by tadhgboyle — APPROVED** [review]

**Comment by tadhgboyle** [comment]
Sorry for the huge delay @intersecato!
If you can get the tests working again I'm happy to merge

**Comment by intersecato** [comment]
Hi, @tadhgboyle,
we've been using the fork in production since the day I opened the pull request and it hasn't given any problems since, changes are stable (Used by more than 100 users everyday).

**Comment by tadhgboyle** [comment]
Thanks a lot for the contribution, glad it's been helpful for you!

**Pull request merged**
